import { GoogleGenAI } from "@google/genai";

const getAiClient = () => {
  const apiKey = process.env.API_KEY;
  if (!apiKey) {
    throw new Error("API Key not found. Please ensure process.env.API_KEY is set.");
  }
  return new GoogleGenAI({ apiKey });
};

const cleanBase64 = (dataUrl: string) => {
  return dataUrl.split(',')[1] || dataUrl;
};

export const removeBackground = async (imageBase64: string): Promise<string> => {
  const ai = getAiClient();
  const model = "gemini-2.5-flash-image";

  try {
    const response = await ai.models.generateContent({
      model: model,
      contents: {
        parts: [
          {
            inlineData: {
              mimeType: "image/jpeg",
              data: cleanBase64(imageBase64)
            }
          },
          {
            text: "Expertly extract the main subject from this image with pixel-perfect precision. Handle fine details like hair, fur, and semi-transparent objects correctly. Return the subject on a fully transparent background (RGBA). Do not crop the subject. Ensure no background artifacts remain."
          }
        ]
      }
    });

    const parts = response.candidates?.[0]?.content?.parts;
    if (parts) {
      for (const part of parts) {
        if (part.inlineData && part.inlineData.data) {
          return `data:image/png;base64,${part.inlineData.data}`;
        }
      }
    }
    
    throw new Error("No image generated by AI.");
  } catch (error) {
    console.error("Gemini Remove BG Error:", error);
    throw error;
  }
};

export const generateAiBackground = async (foregroundImageBase64: string, prompt: string): Promise<string> => {
  const ai = getAiClient();
  const model = "gemini-2.5-flash-image"; 

  try {
    const response = await ai.models.generateContent({
      model: model,
      contents: {
        parts: [
          {
            inlineData: {
              mimeType: "image/png",
              data: cleanBase64(foregroundImageBase64)
            }
          },
          {
            text: `Use the provided transparent image as the foreground layer. Generate a new high-quality background for it based on this description: "${prompt}". Blend the lighting and shadows of the foreground subject realistically into the new background. Return the final composite image.`
          }
        ]
      }
    });

    const parts = response.candidates?.[0]?.content?.parts;
    if (parts) {
      for (const part of parts) {
        if (part.inlineData && part.inlineData.data) {
          return `data:image/png;base64,${part.inlineData.data}`;
        }
      }
    }
    throw new Error("No image generated by AI.");
  } catch (error) {
    console.error("Gemini Gen BG Error:", error);
    throw error;
  }
};